/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:731bb616-45d1-4b4a-bf44-b6db6dcdfc23",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_Sq3YZ0LnV",
    "aws_user_pools_web_client_id": "712jfmocj18t2062ihlqdbp4v4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://shiq6kv7ungarf3whuvinrv44q.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_user_files_s3_bucket": "instagramclonee5d661373d7c47c68704168c28c7685e160336-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
